// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package store

import (
	"github.com/google/uuid"
)

type User struct {
	ID       uuid.UUID `db:"id" json:"id" validate:"uuid"`
	Email    string    `db:"email" json:"email" validate:"required,email"`
	Password string    `db:"password" json:"password" validate:"required"`
}
